### ISSUE TITLE
The name is tendancieux 

### ISSUE THREAD

**Issue by n-peugnet** [SylvainLune/SlipPylos#1]
Excuse me but IMHO the name should be changed for something more correct

**Comment by SylvainJoube** [comment]
Oh, I apologize for you not being able to understand the name of the company, my friend.
It stands for "Syndicat du Logiciel Interactif et Pédagogique", even our teacher found this name to be a good one ! :squid:

**Comment by n-peugnet** [comment]
My bad I thought the name was referring to this: ![SLIP](https://images.calzedonia.com/get/w/2000/4SN422_4778_F.jpg)

**Comment by n-peugnet** [comment]
So I am going to close this issue as it is not a problem finally
